public class CheckDatatypes {
    public void methodBoolean() {
        Boolean checkBoolean = true;
        System.debug('Value of checkBoolean : ' + checkBoolean);
    }
    public void methodInteger() {
        Integer varFirst = 1;
        Integer varSecond = 2;
        System.debug('Value of varfirst : ' + varfirst);
        System.debug('Value of varSecond : ' + varSecond);
    }
    public void stringmethod() {
        String varName = 'Name';
        String var2Name = 'Akshansh';
        System.debug('Value of Name : ' + varName + ' ' + var2Name);
    }
    public void methodId() {
        Id checkId = '0012w00001RjLIgAAN'; //This value can be different from one from your org
        System.debug('Value of checkId : ' + checkId);
    }
    public void methodDouble() {
        Double varFirst = 1.23;
        Double varSecond = 209.764;
        System.debug('Value of varfirst : ' + varfirst);
        System.debug('Value of varSecond : ' + varSecond);
        }
}
