string firstName = 'Vitap';
string lastName = 'Ramdevputra';

string fullName = firstName + ' ' + lastName;  // Vitap Ramdevputra
system.debug('full name is ' + fullName); //full name is Vitap Ramdevputra

//multiple variable
string a,b,c; //declared 3 string variables.
a = 'Akshansh';
system.debug (a);
system.debug(b);
system.debug(c);

string x = 'This', y = 'is', z='simple';
system.debug(x+y+z);